name: Build APKs for release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: 'gradle'

      - name: Accept SDK licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Setup signing configs
        run: |
          echo "$KEYSTORE" | base64 --decode > app/keystore.jks
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
          sed -i "s|storeFile=.*|storeFile=keystore.jks|" keystore.properties
          echo "=== keystore.properties ==="
          cat keystore.properties
          echo "=== keystore.jks exists ==="
          ls -la app/keystore.jks
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

      - name: Clear configuration cache
        run: rm -rf .gradle/configuration-cache
        
      - name: Get date-time string
        id: datetime
        run: |
          DATE_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "date_tag=$DATE_TAG" >> $GITHUB_ENV

      - name: Clone NewPipeExtractor
        run: |
          git clone https://github.com/TeamNewPipe/NewPipeExtractor ../NewPipeExtractor
          cd ../NewPipeExtractor
          git checkout d59dc21
          echo "=== BEFORE PATCH ==="
          head -15 build.gradle
          sed -i '/sourceCompatibility/d' build.gradle
          sed -i '/targetCompatibility/d' build.gradle
          echo "=== AFTER PATCH ==="
          head -15 build.gradle

      - name: Clone ffMetadataEx
        run: git clone https://github.com/OuterTune/ffMetadataEx -b vibebur-128 ../ffMetadataEx

      - name: Clone ffmpeg libs
        run: git clone https://github.com/mikooomich/ffmpeg-android-maker-prebuilt/ -b audio ../ffMetadataEx/ffmpeg-android-maker

      - name: Build ffMetadataEx AAR
        run: |
          cd ../ffMetadataEx
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Clear configuration cache        # ← add this
        run: rm -rf .gradle/configuration-cache

      - name: Build core release APK
        run: ./gradlew assembleCoreRelease

      - name: Build full release APK
        run: ./gradlew assembleFullRelease

      - name: Upload core APK
        uses: actions/upload-artifact@v4
        with:
          name: core-release-apk
          path: app/build/outputs/apk/core/release/*.apk

      - name: Upload full APK
        uses: actions/upload-artifact@v4
        with:
          name: full-release-apk
          path: app/build/outputs/apk/full/release/*.apk
